// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI expects sqlite file URLs for this schema.
    // Runtime Turso connectivity is handled by @prisma/adapter-libsql in lib/prisma.ts.
    url:
      process.env.DATABASE_URL?.startsWith("file:")
        ? process.env.DATABASE_URL
        : "file:./dev.db",
  },
});
